apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.python.service.port }}
      targetPort: {{ .Values.python.service.port }}
      protocol: TCP
  selector:
    app: python
