name: Deploy to Kubernetes via Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.0'

      - name: Setup Minikube
        uses: medyagh/setup-minikube@v2
        with:
          kubernetes-version: 'latest'
          driver: docker
          memory: 6g
          cpus: 4

      - name: Build Docker images
        run: |
          cd ../nodejs-microservice
          docker build -t nodejs-microservice:latest .
          cd ../python-api
          docker build -t python-microservice:latest .
          cd ../my-microservice-app

      - name: Install Helm chart
        run: |
          helm dependency update
          helm install my-release .
